### ISSUE TITLE
i586 error in generated xkb.py: AttributeError: /usr/lib/libX11.so.6: undefined symbol: _XData32

### ISSUE THREAD

**Issue by jayvdb** [hcpl/xkbgroup#13]
On openSUSE Tumbleweed i586 `libX11.so.6` doesnt have symbol `_XData32`, which results in:

```py
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from xkbgroup.version import VERSION
  File "/home/abuild/rpmbuild/BUILD/xkbgroup-0.2.0/xkbgroup/__init__.py", line 14, in <module>
    from .core import XKeyboard, X11Error
  File "/home/abuild/rpmbuild/BUILD/xkbgroup-0.2.0/xkbgroup/core.py", line 31, in <module>
    from xkbgroup.xkb import *
  File "/home/abuild/rpmbuild/BUILD/xkbgroup-0.2.0/xkbgroup/xkb.py", line 4636, in <module>
    _XData32 = _libraries['libX11.so.6']._XData32
  File "/usr/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libX11.so.6: undefined symbol: _XData32
```

**Comment by jayvdb** [comment]
Same occurs for `_XRead32`
